template = "https://github.com/giellalt/template-lang-und"
rev_id = 328
template_sha = "a66ce6606ea33e46cd3439c88cafa44d4dcdde92"

[replacements]
__GLOTTOLOG_ID__ = "sout2978"
__REPO__ = "lang-crj"
__UND2C__ = "crj"
__UNDEFINED__ = "Southern East Cree"
__UND__ = "crj"
