template = "https://github.com/giellalt/template-lang-und"
rev_id = 308
template_sha = "ec3d8dc80df568320da1b4f5034d7f589ea9f666"

[replacements]
__GLOTTOLOG_ID__ = "sout2978"
__REPO__ = "lang-crj"
__UND2C__ = "crj"
__UNDEFINED__ = "Southern East Cree"
__UND__ = "crj"
